import type { Patient, Encounter, Clinician, Lab, Medicine } from './portal-types.ts';
import { labGlossary } from './lab-interpretation.ts';

export function demoPatients(): Patient[] {
  const base = { version: 1, medical_record_number: '', sex: 'female', blood_type: '', phone: '', email: '', address: 'Buffalo, NY (địa chỉ giả lập)', emergency_contact: 'Liên hệ demo · +1 716-555-0100', general_note: 'Hồ sơ hoàn toàn giả lập để thử luồng khám bệnh.', created_at: '', updated_at: '', conditions: [], allergies: [] };
  return [
    { ...base, id: 'patient-anh', medical_record_number: 'MP-0001', display_name: 'Nguyễn Minh Anh', birth_date: '1998-02-14', blood_type: 'O+', conditions: [{ id: 'c1', name: 'Hen phế quản', clinical_term: 'Asthma', since: '2016', status: 'active', note: 'Đã ghi nhận trong hồ sơ demo.' }], allergies: [{ id: 'a1', substance: 'Penicillin', reaction: 'Nổi mề đay', severity: 'moderate', note: 'Theo tiền sử người bệnh khai.' }] },
    { ...base, id: 'patient-tuan', medical_record_number: 'MP-0002', display_name: 'Trần Quốc Tuấn', birth_date: '1971-06-08', sex: 'male', blood_type: 'B+', conditions: [{ id: 'c2', name: 'Đái tháo đường típ 2', clinical_term: 'Type 2 diabetes mellitus', since: '2021', status: 'active', note: 'Theo dõi đường huyết định kỳ.' }], allergies: [] },
    { ...base, id: 'patient-quynh', medical_record_number: 'MP-0003', display_name: 'Lê Ngọc Quỳnh', birth_date: '2004-11-21', blood_type: 'A+', conditions: [{ id: 'c3', name: 'Thiếu máu thiếu sắt', clinical_term: 'Iron deficiency anemia', since: '2026', status: 'active', note: 'Đang theo dõi trong hồ sơ demo.' }], allergies: [] },
    { ...base, id: 'patient-bao', medical_record_number: 'MP-0004', display_name: 'Phạm Gia Bảo', birth_date: '1985-03-19', sex: 'male', blood_type: 'AB+', conditions: [{ id: 'c4', name: 'Tăng huyết áp', clinical_term: 'Hypertension', since: '2023', status: 'active', note: 'Có ghi huyết áp tại nhà.' }], allergies: [{ id: 'a4', substance: 'Tôm', reaction: 'Ngứa, nổi mẩn', severity: 'moderate', note: 'Dị ứng thực phẩm theo lời khai.' }] },
    { ...base, id: 'patient-linh', medical_record_number: 'MP-0005', display_name: 'Võ Thùy Linh', birth_date: '1990-08-27', blood_type: 'O−', conditions: [{ id: 'c5', name: 'Trào ngược dạ dày – thực quản', clinical_term: 'Gastroesophageal reflux disease (GERD)', since: '2024', status: 'active', note: 'Theo dõi theo triệu chứng.' }], allergies: [] },
  ];
}

export const demoClinicians: Clinician[] = [
  { id: 'doctor-lan', name: 'BS. Nguyễn Hoàng Lan', specialty: 'Nội tổng quát', facility: 'Trung tâm Y tế MediPass Demo', public_phone: '+1 716-555-0110', registration: 'DEMO-001 · thông tin giả lập' },
  { id: 'doctor-minh', name: 'BS. Trần Đức Minh', specialty: 'Nội tiết – chuyển hóa', facility: 'Phòng khám MediPass Demo', public_phone: '+1 716-555-0111', registration: 'DEMO-002 · thông tin giả lập' },
  { id: 'doctor-ha', name: 'BS. Phạm Thanh Hà', specialty: 'Y học gia đình', facility: 'Trung tâm Y tế MediPass Demo', public_phone: '+1 716-555-0112', registration: 'DEMO-003 · thông tin giả lập' },
];
function lab(key: string, name: string, value: string, unit: string, low: number | null, high: number | null, note: string): Lab {
  return { id: `lab-${key}`, name, value, unit, reference_low: low, reference_high: high, reference_text: 'Khoảng ví dụ trên phiếu giả lập', ...labGlossary[key], clinician_note: note };
}
function med(name: string, dose: string, frequency: string, status = 'active', duration = 'Theo đơn tại lần khám'): Medicine {
  return { id: `med-${name}`, name, dose, frequency, route: 'Uống', duration, status, instructions: 'Đơn thuốc giả lập; phần hướng dẫn thực tế do bác sĩ ghi khi khám.' };
}
export function demoEncounters(): Encounter[] {
  const base = { id: '', patient_id: '', version: 1, visit_date: '2026-09-08', reason: '', symptoms: '', diagnosis: '', plain_diagnosis: '', treatment_plan: '', follow_up: 'Tái khám theo lịch đã thống nhất.', follow_up_date: '2026-10-06', blood_pressure: '118/76', pulse: '76', temperature: '36.7', weight: '', oxygen_saturation: '98', clinician: demoClinicians[0], labs: [], medications: [], procedures: [], created_at: '', updated_at: '' };
  const recent: Encounter[] = [
    { ...base, id: 'visit-anh-2', patient_id: 'patient-anh', visit_date: '2026-09-08', reason: 'Tái khám hen và rà soát cách dùng thuốc', symptoms: 'Thỉnh thoảng ho khi vận động; không ghi nhận khó thở tại lần khám giả lập.', diagnosis: 'Asthma follow-up', plain_diagnosis: 'Theo dõi hen phế quản', treatment_plan: 'Bác sĩ đã rà soát cách sử dụng dụng cụ hít và ghi nhận nhật ký triệu chứng.', weight: '54', procedures: [{ id: 'p1', name: 'Rà soát kỹ thuật hít thuốc', result: 'Đã thực hành với nhân viên y tế', explanation: 'Kiểm tra thao tác để thuốc đi vào đường thở đúng cách.' }], medications: [{ ...med('Albuterol inhaler', '90 mcg/nhát xịt', 'Theo chỉ định trên đơn'), route: 'Hít', instructions: 'Minh họa thuốc trong hồ sơ hen. Cách dùng cụ thể do bác sĩ xác nhận.' }] },
    { ...base, id: 'visit-tuan-2', patient_id: 'patient-tuan', visit_date: '2026-09-07', reason: 'Theo dõi đường huyết định kỳ', symptoms: 'Khát nước nhẹ, mang theo kết quả xét nghiệm trước khám.', diagnosis: 'Type 2 diabetes mellitus — follow-up', plain_diagnosis: 'Theo dõi bệnh đái tháo đường típ 2', treatment_plan: 'Trao đổi kết quả HbA1c, rà soát thuốc và hẹn đánh giá lại theo mục tiêu cá nhân.', weight: '73', clinician: demoClinicians[1], labs: [lab('hba1c', 'HbA1c', '7.1', '%', 4, 5.6, 'Khoảng tham chiếu khác với mục tiêu điều trị cá nhân. Bác sĩ sẽ trao đổi mục tiêu phù hợp.'), lab('glucose', 'Fasting plasma glucose', '132', 'mg/dL', 70, 99, 'Mẫu giả lập được lấy lúc đói; xem cùng HbA1c.'), lab('creatinine', 'Creatinine', '0.9', 'mg/dL', 0.7, 1.3, 'Đã xem trong buổi khám giả lập.')], medications: [med('Metformin', '500 mg', 'Theo đơn bác sĩ')] },
    { ...base, id: 'visit-quynh-2', patient_id: 'patient-quynh', visit_date: '2026-09-06', reason: 'Mệt mỏi và xem lại công thức máu', symptoms: 'Mệt khi đi bộ xa trong vài tuần; khai ăn uống chưa đều.', diagnosis: 'Iron deficiency anemia — review', plain_diagnosis: 'Tái khám thiếu máu do thiếu sắt', treatment_plan: 'Trao đổi công thức máu, lượng sắt dự trữ và kế hoạch theo dõi nguyên nhân.', weight: '49', clinician: demoClinicians[2], labs: [lab('hemoglobin', 'Hemoglobin (Hb)', '11.2', 'g/dL', 12, 15.5, 'Thấp hơn khoảng trên phiếu giả lập. Cần đánh giá cùng triệu chứng và các chỉ số khác.'), lab('ferritin', 'Ferritin', '10', 'ng/mL', 15, 150, 'Dự trữ sắt thấp hơn khoảng trên phiếu giả lập.')], medications: [med('Ferrous sulfate', 'Theo đơn đã kê', 'Theo đơn bác sĩ', 'active', 'Đánh giá lại ở lần hẹn kế tiếp')] },
    { ...base, id: 'visit-bao-2', patient_id: 'patient-bao', visit_date: '2026-09-05', reason: 'Tái khám huyết áp và mỡ máu', symptoms: 'Mang nhật ký huyết áp tại nhà, không có triệu chứng mới được ghi nhận.', diagnosis: 'Hypertension follow-up', plain_diagnosis: 'Theo dõi huyết áp', treatment_plan: 'Bác sĩ đã xem nhật ký huyết áp, xét nghiệm mỡ máu và rà soát đơn thuốc.', blood_pressure: '136/84', weight: '78', labs: [lab('ldl', 'LDL cholesterol', '128', 'mg/dL', null, 100, 'Giới hạn minh họa trên phiếu; mục tiêu riêng cần bác sĩ xác định.')], medications: [med('Amlodipine', '5 mg', 'Theo đơn bác sĩ')] },
    { ...base, id: 'visit-linh-2', patient_id: 'patient-linh', visit_date: '2026-09-04', reason: 'Tái khám khó chịu sau ăn', symptoms: 'Ợ nóng đã giảm so với lần khám trước; đôi lúc còn khó chịu sau bữa tối.', diagnosis: 'GERD follow-up', plain_diagnosis: 'Theo dõi trào ngược dạ dày – thực quản', treatment_plan: 'Rà soát triệu chứng, thời điểm dùng thuốc và lịch tái khám; ghi nhận điều trị đã kết thúc.', weight: '57', clinician: demoClinicians[2], medications: [med('Omeprazole', '20 mg', 'Theo đơn trước đây', 'completed', 'Đợt điều trị đã hoàn tất')], procedures: [{ id: 'p2', name: 'Khám bụng', result: 'Đã ghi nhận trong buổi khám giả lập', explanation: 'Bác sĩ hỏi triệu chứng và khám vùng bụng để định hướng đánh giá.' }] },
  ];
  const earlier = recent.map((visit, i) => ({ ...visit, id: visit.id.replace('-2', '-1'), visit_date: `2026-08-0${8-i}`, reason: 'Khám ban đầu và lập kế hoạch theo dõi', symptoms: 'Ghi nhận triệu chứng và tiền sử tại lần khám đầu.', follow_up_date: visit.visit_date, labs: visit.labs.map(l => ({ ...l, value: l.name === 'HbA1c' ? '7.6' : l.name === 'Hemoglobin (Hb)' ? '10.8' : l.value })), medications: visit.medications.map(m => ({ ...m, status: 'active' })), treatment_plan: 'Đã ghi nhận tiền sử chung, giải thích các bước theo dõi và hẹn tái khám.' }));
  return [...recent, ...earlier];
}
