import type { Patient, Encounter, Clinician, Lab, Medicine } from './portal-types.ts';
import { labGlossary } from './lab-interpretation.ts';

export function demoPatients(): Patient[] {
  const base = { version: 1, medical_record_number: '', sex: 'female', blood_type: '', phone: '', email: '', address: 'Buffalo, NY (simulated address)', emergency_contact: 'Demo contact · +1 716-555-0100', general_note: 'Fully synthetic record for testing the clinical workflow.', created_at: '', updated_at: '', conditions: [], allergies: [] };
  return [
    { ...base, id: 'patient-anh', medical_record_number: 'MP-0001', display_name: 'Emily Carter', birth_date: '1998-02-14', blood_type: 'O+', conditions: [{ id: 'c1', name: 'Asthma', clinical_term: 'Asthma', since: '2016', status: 'active', note: 'Recorded in the demo chart.' }], allergies: [{ id: 'a1', substance: 'Penicillin', reaction: 'Hives', severity: 'moderate', note: 'Based on patient-reported history.' }] },
    { ...base, id: 'patient-tuan', medical_record_number: 'MP-0002', display_name: 'Michael Johnson', birth_date: '1971-06-08', sex: 'male', blood_type: 'B+', conditions: [{ id: 'c2', name: 'Type 2 diabetes', clinical_term: 'Type 2 diabetes mellitus', since: '2021', status: 'active', note: 'Routine blood glucose monitoring.' }], allergies: [] },
    { ...base, id: 'patient-quynh', medical_record_number: 'MP-0003', display_name: 'Sophia Martinez', birth_date: '2004-11-21', blood_type: 'A+', conditions: [{ id: 'c3', name: 'Iron deficiency anemia', clinical_term: 'Iron deficiency anemia', since: '2026', status: 'active', note: 'Being monitored in this demo record.' }], allergies: [] },
    { ...base, id: 'patient-bao', medical_record_number: 'MP-0004', display_name: 'Daniel Brooks', birth_date: '1985-03-19', sex: 'male', blood_type: 'AB+', conditions: [{ id: 'c4', name: 'Hypertension', clinical_term: 'Hypertension', since: '2023', status: 'active', note: 'Home blood pressure readings are available.' }], allergies: [{ id: 'a4', substance: 'Shrimp', reaction: 'Itching and rash', severity: 'moderate', note: 'Patient-reported food allergy.' }] },
    { ...base, id: 'patient-linh', medical_record_number: 'MP-0005', display_name: 'Olivia Bennett', birth_date: '1990-08-27', blood_type: 'O−', conditions: [{ id: 'c5', name: 'Gastroesophageal reflux', clinical_term: 'Gastroesophageal reflux disease (GERD)', since: '2024', status: 'active', note: 'Monitored according to symptoms.' }], allergies: [] },
  ];
}

export const demoClinicians: Clinician[] = [
  { id: 'doctor-lan', name: 'Dr. Sarah Wilson', specialty: 'Internal Medicine', facility: 'MediPass Demo Medical Center', public_phone: '+1 716-555-0110', registration: 'DEMO-001 · simulated information' },
  { id: 'doctor-minh', name: 'Dr. James Anderson', specialty: 'Endocrinology & Metabolism', facility: 'MediPass Demo Clinic', public_phone: '+1 716-555-0111', registration: 'DEMO-002 · simulated information' },
  { id: 'doctor-ha', name: 'Dr. Emily Clark', specialty: 'Family Medicine', facility: 'MediPass Demo Medical Center', public_phone: '+1 716-555-0112', registration: 'DEMO-003 · simulated information' },
];
function lab(key: string, name: string, value: string, unit: string, low: number | null, high: number | null, note: string): Lab {
  return { id: `lab-${key}`, name, value, unit, reference_low: low, reference_high: high, reference_text: 'Example range from the simulated laboratory report', ...labGlossary[key], clinician_note: note };
}
function med(name: string, dose: string, frequency: string, status = 'active', duration = 'As prescribed at this visit'): Medicine {
  return { id: `med-${name}`, name, dose, frequency, route: 'Oral', duration, status, instructions: 'Simulated prescription; actual instructions are entered by the treating clinician.' };
}
export function demoEncounters(): Encounter[] {
  const base = { id: '', patient_id: '', version: 1, visit_date: '2026-09-08', reason: '', symptoms: '', diagnosis: '', plain_diagnosis: '', treatment_plan: '', follow_up: 'Follow up according to the agreed schedule.', follow_up_date: '2026-10-06', blood_pressure: '118/76', pulse: '76', temperature: '36.7', weight: '', oxygen_saturation: '98', clinician: demoClinicians[0], labs: [], medications: [], procedures: [], created_at: '', updated_at: '' };
  const recent: Encounter[] = [
    { ...base, id: 'visit-anh-2', patient_id: 'patient-anh', visit_date: '2026-09-08', reason: 'Asthma follow-up and inhaler review', symptoms: 'Occasional cough during exercise; no shortness of breath recorded at this simulated visit.', diagnosis: 'Asthma follow-up', plain_diagnosis: 'Asthma follow-up', treatment_plan: 'The clinician reviewed inhaler technique and the symptom diary.', weight: '54', procedures: [{ id: 'p1', name: 'Inhaler technique review', result: 'Practiced with a healthcare professional', explanation: 'The technique was checked to help medicine reach the airways correctly.' }], medications: [{ ...med('Albuterol inhaler', '90 mcg/actuation', 'As directed on the prescription'), route: 'Inhaled', instructions: 'Simulated asthma medication. Exact use must be confirmed by the clinician.' }] },
    { ...base, id: 'visit-tuan-2', patient_id: 'patient-tuan', visit_date: '2026-09-07', reason: 'Routine blood glucose monitoring', symptoms: 'Mild thirst; brought laboratory results to the visit.', diagnosis: 'Type 2 diabetes mellitus — follow-up', plain_diagnosis: 'Type 2 diabetes follow-up', treatment_plan: 'Reviewed HbA1c, medications, and the timing of reassessment against the patient’s individual goal.', weight: '73', clinician: demoClinicians[1], labs: [lab('hba1c', 'HbA1c', '7.1', '%', 4, 5.6, 'The reference range differs from an individual diabetes treatment target. The clinician will discuss the appropriate goal.'), lab('glucose', 'Fasting plasma glucose', '132', 'mg/dL', 70, 99, 'The simulated sample was fasting; interpret it together with HbA1c.'), lab('creatinine', 'Creatinine', '0.9', 'mg/dL', 0.7, 1.3, 'Reviewed during the simulated visit.')], medications: [med('Metformin', '500 mg', 'As prescribed')] },
    { ...base, id: 'visit-quynh-2', patient_id: 'patient-quynh', visit_date: '2026-09-06', reason: 'Fatigue and complete blood count review', symptoms: 'Tired when walking long distances for several weeks; reported irregular meals.', diagnosis: 'Iron deficiency anemia — review', plain_diagnosis: 'Iron deficiency anemia follow-up', treatment_plan: 'Reviewed blood counts, iron stores, and the plan to evaluate the underlying cause.', weight: '49', clinician: demoClinicians[2], labs: [lab('hemoglobin', 'Hemoglobin (Hb)', '11.2', 'g/dL', 12, 15.5, 'Below the range on this simulated report. Review it with symptoms and related measures.'), lab('ferritin', 'Ferritin', '10', 'ng/mL', 15, 150, 'Iron stores are below the range on this simulated report.')], medications: [med('Ferrous sulfate', 'As prescribed', 'As prescribed', 'active', 'Review at the next appointment')] },
    { ...base, id: 'visit-bao-2', patient_id: 'patient-bao', visit_date: '2026-09-05', reason: 'Blood pressure and cholesterol follow-up', symptoms: 'Brought a home blood pressure log; no new symptoms recorded.', diagnosis: 'Hypertension follow-up', plain_diagnosis: 'Blood pressure follow-up', treatment_plan: 'The clinician reviewed the home blood pressure log, lipid result, and medication list.', blood_pressure: '136/84', weight: '78', labs: [lab('ldl', 'LDL cholesterol', '128', 'mg/dL', null, 100, 'Illustrative report limit; an individual target needs clinician confirmation.')], medications: [med('Amlodipine', '5 mg', 'As prescribed')] },
    { ...base, id: 'visit-linh-2', patient_id: 'patient-linh', visit_date: '2026-09-04', reason: 'Follow-up for discomfort after meals', symptoms: 'Heartburn has improved since the previous visit, with occasional discomfort after dinner.', diagnosis: 'GERD follow-up', plain_diagnosis: 'Gastroesophageal reflux follow-up', treatment_plan: 'Reviewed symptoms, medication timing, and follow-up schedule; prior treatment marked complete.', weight: '57', clinician: demoClinicians[2], medications: [med('Omeprazole', '20 mg', 'Previously prescribed', 'completed', 'Treatment course completed')], procedures: [{ id: 'p2', name: 'Abdominal examination', result: 'Recorded during the simulated visit', explanation: 'The clinician reviewed symptoms and examined the abdomen to guide the assessment.' }] },
  ];
  const earlier = recent.map((visit, i) => ({ ...visit, id: visit.id.replace('-2', '-1'), visit_date: `2026-08-0${8-i}`, reason: 'Initial visit and monitoring plan', symptoms: 'Symptoms and medical history were recorded at the initial visit.', follow_up_date: visit.visit_date, labs: visit.labs.map(l => ({ ...l, value: l.name === 'HbA1c' ? '7.6' : l.name === 'Hemoglobin (Hb)' ? '10.8' : l.value })), medications: visit.medications.map(m => ({ ...m, status: 'active' })), treatment_plan: 'Shared history was recorded, monitoring steps were explained, and a follow-up was scheduled.' }));
  return [...recent, ...earlier];
}
