'use client';
import { useState, type SyntheticEvent } from 'react';
import type { Encounter, Clinician, Patient, Lab, Medicine } from '@/lib/portal-types';
import { labGlossary } from '@/lib/lab-interpretation';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { AddButton, RemoveButton, Field, Input, ErrorBox, api, uid, medicineLabels } from './portal-ui';

export function blankEncounter(patient: Patient, doctor?: Clinician): Encounter {
  return { id: uid(), patient_id: patient.id, version: 0, visit_date: new Date().toISOString().slice(0,10), reason: '', symptoms: '', diagnosis: '', plain_diagnosis: '', treatment_plan: '', follow_up: '', follow_up_date: '', blood_pressure: '', pulse: '', temperature: '', weight: '', oxygen_saturation: '', clinician: doctor ? { ...doctor } : { id: uid(), name: '', specialty: '', facility: '', public_phone: '', registration: '' }, labs: [], medications: [], procedures: [], created_at: '', updated_at: '' };
}
export function EncounterForm({ initial, patient, doctors, currentMedications, onClose, onSaved }: { initial: Encounter; patient: Patient; doctors: Clinician[]; currentMedications: Medicine[]; onClose: () => void; onSaved: (encounter: Encounter) => void }) {
  const [value, setValue] = useState<Encounter>(structuredClone(initial));
  const [tab, setTab] = useState('clinical'), [dirty, setDirty] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState('');
  function change(patch: Partial<Encounter>) { setDirty(true); setValue(old => ({ ...old, ...patch })); }
  function close() { if (!saving && (!dirty || window.confirm('Lần khám này có thay đổi chưa lưu. Đóng và bỏ các thay đổi này?'))) onClose(); }
  async function submit(event: SyntheticEvent<HTMLFormElement>) {
    event.preventDefault(); setError('');
    if (!value.reason.trim() || !value.visit_date) { setTab('clinical'); setError('Vui lòng nhập ngày khám và lý do khám.'); return; }
    if (!value.clinician.name.trim() || !value.clinician.facility.trim()) { setTab('doctor'); setError('Vui lòng nhập tên bác sĩ và cơ sở khám.'); return; }
    const incompleteLab = value.labs.some(l => !l.name.trim() || !l.value.trim());
    if (incompleteLab) { setTab('labs'); setError('Mỗi xét nghiệm cần có tên và kết quả.'); return; }
    if (value.medications.some(m => !m.name.trim())) { setTab('medicines'); setError('Vui lòng nhập tên thuốc.'); return; }
    if (value.procedures.some(p => !p.name.trim())) { setTab('procedures'); setError('Vui lòng nhập tên dịch vụ / thủ thuật.'); return; }
    setSaving(true);
    try { const data = await api<{ encounter: Encounter }>('/api/portal/encounters', value); onSaved(data.encounter); } catch (e) { setError((e as Error).message); } finally { setSaving(false); }
  }
  const doctorChange = (patch: Partial<Clinician>) => change({ clinician: { ...value.clinician, ...patch } });
  function addLab() { change({ labs: [...value.labs, { id: uid(), name: '', plain_name: '', value: '', unit: '', reference_low: null, reference_high: null, reference_text: '', explanation: '', clinician_note: '', source_url: '' }] }); }
  function copyMedicines() {
    const key = (m: Medicine) => `${m.name.trim()}|${m.dose.trim()}|${m.route.trim()}`.toLowerCase();
    const existing = new Set(value.medications.map(key));
    change({ medications: [...value.medications, ...currentMedications.filter(m => !existing.has(key(m))).map(m => ({ ...m, id: uid() }))] });
    setTab('medicines');
  }
  return <Dialog open onOpenChange={open => { if (!open) close(); }}><DialogContent className="mp-form-dialog sm:max-w-[980px]" showCloseButton={!saving}><DialogTitle>{initial.version ? 'Chỉnh sửa lần khám' : 'Ghi nhận lần khám mới'}</DialogTitle><DialogDescription>{patient.display_name} · {patient.medical_record_number}. Toàn bộ nội dung của lần khám được lưu cùng nhau.</DialogDescription>
    <div className="mp-form-context"><b>Thông tin chung đã có</b><span>Bệnh nền: {patient.conditions.map(c => c.name).join(', ') || 'Chưa ghi nhận'}</span><span>Dị ứng: {patient.allergies.map(a => a.substance).join(', ') || 'Chưa ghi nhận'}</span></div>
    {!initial.version && currentMedications.length > 0 && <Button type="button" variant="outline" disabled={saving} onClick={copyMedicines}>Lấy {currentMedications.length} thuốc đang dùng để rà soát</Button>}
    <form onSubmit={submit}><fieldset disabled={saving}><Tabs value={tab} onValueChange={v => setTab(String(v))}><TabsList className="mp-form-tabs"><TabsTrigger value="clinical">Lần khám</TabsTrigger><TabsTrigger value="labs">Xét nghiệm ({value.labs.length})</TabsTrigger><TabsTrigger value="medicines">Thuốc ({value.medications.length})</TabsTrigger><TabsTrigger value="procedures">Dịch vụ ({value.procedures.length})</TabsTrigger><TabsTrigger value="doctor">Bác sĩ</TabsTrigger></TabsList>
      <TabsContent value="clinical"><div className="mp-form-grid"><Field label="Ngày khám *"><Input type="date" value={value.visit_date} onChange={e => change({ visit_date: e.target.value })} /></Field><Field label="Lý do khám *"><Input placeholder="VD: Tái khám và xem kết quả xét nghiệm" value={value.reason} onChange={e => change({ reason: e.target.value })} /></Field><Field label="Triệu chứng người bệnh khai"><textarea className="mp-input" rows={3} value={value.symptoms} onChange={e => change({ symptoms: e.target.value })} /></Field><Field label="Chẩn đoán / nhận định chuyên môn"><textarea className="mp-input" rows={3} value={value.diagnosis} onChange={e => change({ diagnosis: e.target.value })} /></Field></div>
        <Field label="Giải thích chẩn đoán cho bệnh nhân" hint="Giữ thuật ngữ gốc ở trên; thêm câu giải thích đơn giản tại đây."><textarea className="mp-input" rows={2} value={value.plain_diagnosis} onChange={e => change({ plain_diagnosis: e.target.value })} /></Field>
        <h3 className="mp-form-subtitle">Chỉ số ghi nhận khi khám</h3><div className="mp-vitals-form">{([['blood_pressure', 'Huyết áp (mmHg)', '120/80'], ['pulse', 'Mạch (lần/phút)', '76'], ['temperature', 'Nhiệt độ (°C)', '36.7'], ['weight', 'Cân nặng (kg)', '60'], ['oxygen_saturation', 'SpO₂ (%)', '98']] as const).map(([key, label, placeholder]) => <Field key={key} label={label}><Input value={value[key]} placeholder={placeholder} onChange={e => change({ [key]: e.target.value })} /></Field>)}</div>
        <Field label="Kế hoạch điều trị / hướng dẫn của bác sĩ"><textarea className="mp-input" rows={4} value={value.treatment_plan} onChange={e => change({ treatment_plan: e.target.value })} /></Field><div className="mp-form-grid"><Field label="Ngày hẹn tiếp"><Input type="date" value={value.follow_up_date} onChange={e => change({ follow_up_date: e.target.value })} /></Field><Field label="Nội dung theo dõi / tái khám"><textarea className="mp-input" value={value.follow_up} onChange={e => change({ follow_up: e.target.value })} /></Field></div>
      </TabsContent>
      <TabsContent value="labs"><div className="mp-section-heading"><div><h3>Kết quả & chú giải xét nghiệm</h3><p>Nhập khoảng tham chiếu đúng trên phiếu, cùng đơn vị với kết quả.</p></div><AddButton onClick={addLab}>Thêm xét nghiệm</AddButton></div>{value.labs.length === 0 && <p className="mp-empty-inline">Lần khám này chưa có xét nghiệm. Bấm “Thêm xét nghiệm” để nhập.</p>}{value.labs.map((lab, i) => {
        const update = (patch: Partial<Lab>) => change({ labs: value.labs.map((x, j) => i === j ? { ...x, ...patch } : x) });
        return <div className="mp-form-row" key={lab.id}><div className="mp-row-title"><strong>Xét nghiệm {i+1}</strong><RemoveButton label={`Bỏ xét nghiệm ${i+1}`} onClick={() => change({ labs: value.labs.filter((_, j) => i !== j) })} /></div><div className="mp-form-grid"><Field label="Tên chuyên môn *"><Input value={lab.name} onChange={e => update({ name: e.target.value })} /></Field><Field label="Gợi ý chú giải"><select className="mp-input" value="" onChange={e => { const guide = labGlossary[e.target.value]; if (guide) update(guide); }}><option value="">Chọn thuật ngữ để điền chú giải</option>{Object.entries(labGlossary).map(([key, guide]) => <option key={key} value={key}>{key.toUpperCase()} · {guide.plain_name}</option>)}</select></Field><Field label="Tên dễ hiểu"><Input value={lab.plain_name} onChange={e => update({ plain_name: e.target.value })} /></Field><Field label="Kết quả *"><Input value={lab.value} onChange={e => update({ value: e.target.value })} /></Field></div><div className="mp-form-grid three"><Field label="Đơn vị"><Input value={lab.unit} placeholder="VD: mg/dL" onChange={e => update({ unit: e.target.value })} /></Field><Field label="Giới hạn dưới"><Input type="number" step="any" value={lab.reference_low ?? ''} onChange={e => update({ reference_low: e.target.value === '' ? null : Number(e.target.value) })} /></Field><Field label="Giới hạn trên"><Input type="number" step="any" value={lab.reference_high ?? ''} onChange={e => update({ reference_high: e.target.value === '' ? null : Number(e.target.value) })} /></Field></div><Field label="Ghi chú khoảng tham chiếu"><Input value={lab.reference_text} placeholder="VD: Mẫu lúc đói; khoảng tham chiếu của phòng xét nghiệm" onChange={e => update({ reference_text: e.target.value })} /></Field><Field label="Giải thích xét nghiệm đo điều gì"><textarea className="mp-input" rows={2} value={lab.explanation} onChange={e => update({ explanation: e.target.value })} /></Field><Field label="Bác sĩ giải thích kết quả này"><textarea className="mp-input" rows={2} value={lab.clinician_note} onChange={e => update({ clinician_note: e.target.value })} /></Field><Field label="Nguồn giải thích (HTTPS, nếu có)"><Input type="url" value={lab.source_url} onChange={e => update({ source_url: e.target.value })} /></Field></div>;
      })}</TabsContent>
      <TabsContent value="medicines"><div className="mp-section-heading"><div><h3>Thuốc tại lần khám</h3><p>Đánh dấu đã ngừng / hoàn tất để cập nhật danh sách đang dùng.</p></div><AddButton onClick={() => change({ medications: [...value.medications, { id: uid(), name: '', dose: '', route: 'Uống', frequency: '', duration: '', status: 'active', instructions: '' }] })}>Thêm thuốc</AddButton></div>{value.medications.length === 0 && <p className="mp-empty-inline">Chưa ghi nhận thuốc tại lần khám này.</p>}{value.medications.map((m, i) => { const update = (patch: Partial<typeof m>) => change({ medications: value.medications.map((x, j) => i === j ? { ...x, ...patch } : x) }); return <div className="mp-form-row" key={m.id}><div className="mp-row-title"><strong>Thuốc {i+1}</strong><RemoveButton label={`Bỏ thuốc ${i+1}`} onClick={() => change({ medications: value.medications.filter((_, j) => i !== j) })} /></div><div className="mp-form-grid">{([['name','Tên thuốc *'],['dose','Hàm lượng / liều ghi trên đơn'],['route','Đường dùng'],['frequency','Tần suất dùng'],['duration','Thời gian dùng']] as const).map(([key,label]) => <Field key={key} label={label}><Input value={m[key]} onChange={e => update({ [key]: e.target.value })} /></Field>)}<Field label="Trạng thái"><select className="mp-input" value={m.status} onChange={e => update({ status: e.target.value })}>{Object.entries(medicineLabels).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></Field></div><Field label="Hướng dẫn cụ thể của bác sĩ"><textarea className="mp-input" rows={2} value={m.instructions} onChange={e => update({ instructions: e.target.value })} /></Field></div>; })}</TabsContent>
      <TabsContent value="procedures"><div className="mp-section-heading"><h3>Dịch vụ / thủ thuật đã thực hiện</h3><AddButton onClick={() => change({ procedures: [...value.procedures, { id: uid(), name: '', result: '', explanation: '' }] })}>Thêm dịch vụ</AddButton></div>{value.procedures.length === 0 && <p className="mp-empty-inline">Chưa ghi nhận dịch vụ bổ sung.</p>}{value.procedures.map((p, i) => { const update = (patch: Partial<typeof p>) => change({ procedures: value.procedures.map((x, j) => i === j ? { ...x, ...patch } : x) }); return <div className="mp-form-row" key={p.id}><div className="mp-row-title"><strong>Dịch vụ {i+1}</strong><RemoveButton label={`Bỏ dịch vụ ${i+1}`} onClick={() => change({ procedures: value.procedures.filter((_, j) => i !== j) })} /></div><Field label="Tên chuyên môn *"><Input value={p.name} onChange={e => update({ name: e.target.value })} /></Field><Field label="Kết quả / nội dung đã làm"><textarea className="mp-input" rows={3} value={p.result} onChange={e => update({ result: e.target.value })} /></Field><Field label="Giải thích dễ hiểu"><textarea className="mp-input" rows={2} value={p.explanation} onChange={e => update({ explanation: e.target.value })} /></Field></div>; })}</TabsContent>
      <TabsContent value="doctor"><Field label="Chọn bác sĩ đã có"><select className="mp-input" value={doctors.some(d => d.id === value.clinician.id) ? value.clinician.id : ''} onChange={e => { const doctor = doctors.find(d => d.id === e.target.value); change({ clinician: doctor ? { ...doctor } : { id: uid(), name: '', specialty: '', facility: '', public_phone: '', registration: '' } }); }}><option value="">Nhập bác sĩ mới</option>{doctors.map(d => <option value={d.id} key={d.id}>{d.name} · {d.facility}</option>)}</select></Field><div className="mp-form-grid">{([['name','Tên bác sĩ *'],['specialty','Chuyên khoa'],['facility','Bệnh viện / phòng khám *'],['public_phone','Số liên hệ công khai'],['registration','Mã hành nghề / thông tin công khai']] as const).map(([key,label]) => <Field key={key} label={label}><Input value={value.clinician[key]} onChange={e => doctorChange({ [key]: e.target.value })} /></Field>)}</div><p className="mp-footnote">Thông tin bác sĩ được giữ theo thời điểm khám để người bệnh biết ai đã khám và kê đơn.</p></TabsContent>
    </Tabs></fieldset><ErrorBox message={error} /><div className="mp-form-footer"><span>{dirty ? 'Có thay đổi chưa lưu' : 'Thông tin của một lần khám'}</span><Button type="button" variant="outline" disabled={saving} onClick={close}>Hủy</Button><Button type="submit" disabled={saving}>{saving ? 'Đang lưu toàn bộ…' : 'Lưu lần khám'}</Button></div></form>
  </DialogContent></Dialog>;
}
