'use client';
import { useState, type SyntheticEvent } from 'react';
import type { Encounter, Clinician, Patient, Lab, Medicine } from '@/lib/portal-types';
import { labGlossary } from '@/lib/lab-interpretation';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { AddButton, RemoveButton, Field, Input, ErrorBox, api, uid, medicineLabels } from './portal-ui';

export function blankEncounter(patient: Patient, doctor?: Clinician): Encounter {
  return { id: uid(), patient_id: patient.id, version: 0, visit_date: new Date().toISOString().slice(0,10), reason: '', symptoms: '', diagnosis: '', plain_diagnosis: '', treatment_plan: '', follow_up: '', follow_up_date: '', blood_pressure: '', pulse: '', temperature: '', weight: '', oxygen_saturation: '', clinician: doctor ? { ...doctor } : { id: uid(), name: '', specialty: '', facility: '', public_phone: '', registration: '' }, labs: [], medications: [], procedures: [], created_at: '', updated_at: '' };
}
export function EncounterForm({ initial, patient, doctors, currentMedications, onClose, onSaved }: { initial: Encounter; patient: Patient; doctors: Clinician[]; currentMedications: Medicine[]; onClose: () => void; onSaved: (encounter: Encounter) => void }) {
  const [value, setValue] = useState<Encounter>(structuredClone(initial));
  const [tab, setTab] = useState('clinical'), [dirty, setDirty] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState('');
  function change(patch: Partial<Encounter>) { setDirty(true); setValue(old => ({ ...old, ...patch })); }
  function close() { if (!saving && (!dirty || window.confirm('This visit has unsaved changes. Close and discard them?'))) onClose(); }
  async function submit(event: SyntheticEvent<HTMLFormElement>) {
    event.preventDefault(); setError('');
    if (!value.reason.trim() || !value.visit_date) { setTab('clinical'); setError('Enter the visit date and reason for the visit.'); return; }
    if (!value.clinician.name.trim() || !value.clinician.facility.trim()) { setTab('doctor'); setError('Enter the clinician name and facility.'); return; }
    const incompleteLab = value.labs.some(l => !l.name.trim() || !l.value.trim());
    if (incompleteLab) { setTab('labs'); setError('Every lab entry needs a name and result.'); return; }
    if (value.medications.some(m => !m.name.trim())) { setTab('medicines'); setError('Enter a medication name.'); return; }
    if (value.procedures.some(p => !p.name.trim())) { setTab('procedures'); setError('Enter a service or procedure name.'); return; }
    setSaving(true);
    try { const data = await api<{ encounter: Encounter }>('/api/portal/encounters', value); onSaved(data.encounter); } catch (e) { setError((e as Error).message); } finally { setSaving(false); }
  }
  const doctorChange = (patch: Partial<Clinician>) => change({ clinician: { ...value.clinician, ...patch } });
  function addLab() { change({ labs: [...value.labs, { id: uid(), name: '', plain_name: '', value: '', unit: '', reference_low: null, reference_high: null, reference_text: '', explanation: '', clinician_note: '', source_url: '' }] }); }
  function copyMedicines() {
    const key = (m: Medicine) => `${m.name.trim()}|${m.dose.trim()}|${m.route.trim()}`.toLowerCase();
    const existing = new Set(value.medications.map(key));
    change({ medications: [...value.medications, ...currentMedications.filter(m => !existing.has(key(m))).map(m => ({ ...m, id: uid() }))] });
    setTab('medicines');
  }
  return <Dialog open onOpenChange={open => { if (!open) close(); }}><DialogContent className="mp-form-dialog sm:max-w-[980px]" showCloseButton={!saving}><DialogTitle>{initial.version ? 'Edit visit' : 'Record a new visit'}</DialogTitle><DialogDescription>{patient.display_name} · {patient.medical_record_number}. All information from this visit is saved together.</DialogDescription>
    <div className="mp-form-context"><b>Shared information on file</b><span>Conditions: {patient.conditions.map(c => c.name).join(', ') || 'None recorded'}</span><span>Allergies: {patient.allergies.map(a => a.substance).join(', ') || 'None recorded'}</span></div>
    {!initial.version && currentMedications.length > 0 && <Button type="button" variant="outline" disabled={saving} onClick={copyMedicines}>Copy {currentMedications.length} current medications for review</Button>}
    <form onSubmit={submit}><fieldset disabled={saving}><Tabs value={tab} onValueChange={v => setTab(String(v))}><TabsList className="mp-form-tabs"><TabsTrigger value="clinical">Visit</TabsTrigger><TabsTrigger value="labs">Labs ({value.labs.length})</TabsTrigger><TabsTrigger value="medicines">Medications ({value.medications.length})</TabsTrigger><TabsTrigger value="procedures">Services ({value.procedures.length})</TabsTrigger><TabsTrigger value="doctor">Clinician</TabsTrigger></TabsList>
      <TabsContent value="clinical"><div className="mp-form-grid"><Field label="Visit date *"><Input type="date" value={value.visit_date} onChange={e => change({ visit_date: e.target.value })} /></Field><Field label="Reason for visit *"><Input placeholder="Example: Follow-up and lab review" value={value.reason} onChange={e => change({ reason: e.target.value })} /></Field><Field label="Symptoms reported by the patient"><textarea className="mp-input" rows={3} value={value.symptoms} onChange={e => change({ symptoms: e.target.value })} /></Field><Field label="Diagnosis / clinical assessment"><textarea className="mp-input" rows={3} value={value.diagnosis} onChange={e => change({ diagnosis: e.target.value })} /></Field></div>
        <Field label="Plain-language explanation for the patient" hint="Keep the original clinical term above and add a simple explanation here."><textarea className="mp-input" rows={2} value={value.plain_diagnosis} onChange={e => change({ plain_diagnosis: e.target.value })} /></Field>
        <h3 className="mp-form-subtitle">Vitals recorded during the visit</h3><div className="mp-vitals-form">{([['blood_pressure', 'Blood pressure (mmHg)', '120/80'], ['pulse', 'Pulse (beats/min)', '76'], ['temperature', 'Temperature (°C)', '36.7'], ['weight', 'Weight (kg)', '60'], ['oxygen_saturation', 'SpO₂ (%)', '98']] as const).map(([key, label, placeholder]) => <Field key={key} label={label}><Input value={value[key]} placeholder={placeholder} onChange={e => change({ [key]: e.target.value })} /></Field>)}</div>
        <Field label="Treatment plan / clinician instructions"><textarea className="mp-input" rows={4} value={value.treatment_plan} onChange={e => change({ treatment_plan: e.target.value })} /></Field><div className="mp-form-grid"><Field label="Next appointment"><Input type="date" value={value.follow_up_date} onChange={e => change({ follow_up_date: e.target.value })} /></Field><Field label="Monitoring / follow-up details"><textarea className="mp-input" value={value.follow_up} onChange={e => change({ follow_up: e.target.value })} /></Field></div>
      </TabsContent>
      <TabsContent value="labs"><div className="mp-section-heading"><div><h3>Lab results & explanations</h3><p>Enter the reference range exactly as reported, using the same unit as the result.</p></div><AddButton onClick={addLab}>Add lab result</AddButton></div>{value.labs.length === 0 && <p className="mp-empty-inline">No lab results are recorded for this visit. Select “Add lab result” to enter one.</p>}{value.labs.map((lab, i) => {
        const update = (patch: Partial<Lab>) => change({ labs: value.labs.map((x, j) => i === j ? { ...x, ...patch } : x) });
        return <div className="mp-form-row" key={lab.id}><div className="mp-row-title"><strong>Lab result {i+1}</strong><RemoveButton label={`Remove lab result ${i+1}`} onClick={() => change({ labs: value.labs.filter((_, j) => i !== j) })} /></div><div className="mp-form-grid"><Field label="Clinical name *"><Input value={lab.name} onChange={e => update({ name: e.target.value })} /></Field><Field label="Explanation template"><select className="mp-input" value="" onChange={e => { const guide = labGlossary[e.target.value]; if (guide) update(guide); }}><option value="">Choose a term to fill the explanation</option>{Object.entries(labGlossary).map(([key, guide]) => <option key={key} value={key}>{key.toUpperCase()} · {guide.plain_name}</option>)}</select></Field><Field label="Plain-language name"><Input value={lab.plain_name} onChange={e => update({ plain_name: e.target.value })} /></Field><Field label="Result *"><Input value={lab.value} onChange={e => update({ value: e.target.value })} /></Field></div><div className="mp-form-grid three"><Field label="Unit"><Input value={lab.unit} placeholder="Example: mg/dL" onChange={e => update({ unit: e.target.value })} /></Field><Field label="Lower limit"><Input type="number" step="any" value={lab.reference_low ?? ''} onChange={e => update({ reference_low: e.target.value === '' ? null : Number(e.target.value) })} /></Field><Field label="Upper limit"><Input type="number" step="any" value={lab.reference_high ?? ''} onChange={e => update({ reference_high: e.target.value === '' ? null : Number(e.target.value) })} /></Field></div><Field label="Reference-range note"><Input value={lab.reference_text} placeholder="Example: Fasting specimen; laboratory reference range" onChange={e => update({ reference_text: e.target.value })} /></Field><Field label="Explain what this test measures"><textarea className="mp-input" rows={2} value={lab.explanation} onChange={e => update({ explanation: e.target.value })} /></Field><Field label="Clinician explanation of this result"><textarea className="mp-input" rows={2} value={lab.clinician_note} onChange={e => update({ clinician_note: e.target.value })} /></Field><Field label="Explanation source (HTTPS, if available)"><Input type="url" value={lab.source_url} onChange={e => update({ source_url: e.target.value })} /></Field></div>;
      })}</TabsContent>
      <TabsContent value="medicines"><div className="mp-section-heading"><div><h3>Medications at this visit</h3><p>Mark a medication as stopped or completed to update the current list.</p></div><AddButton onClick={() => change({ medications: [...value.medications, { id: uid(), name: '', dose: '', route: 'Oral', frequency: '', duration: '', status: 'active', instructions: '' }] })}>Add medication</AddButton></div>{value.medications.length === 0 && <p className="mp-empty-inline">No medications are recorded for this visit.</p>}{value.medications.map((m, i) => { const update = (patch: Partial<typeof m>) => change({ medications: value.medications.map((x, j) => i === j ? { ...x, ...patch } : x) }); return <div className="mp-form-row" key={m.id}><div className="mp-row-title"><strong>Medication {i+1}</strong><RemoveButton label={`Remove medication ${i+1}`} onClick={() => change({ medications: value.medications.filter((_, j) => i !== j) })} /></div><div className="mp-form-grid">{([['name','Medication name *'],['dose','Strength / prescribed dose'],['route','Route'],['frequency','Frequency'],['duration','Duration']] as const).map(([key,label]) => <Field key={key} label={label}><Input value={m[key]} onChange={e => update({ [key]: e.target.value })} /></Field>)}<Field label="Status"><select className="mp-input" value={m.status} onChange={e => update({ status: e.target.value })}>{Object.entries(medicineLabels).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></Field></div><Field label="Specific clinician instructions"><textarea className="mp-input" rows={2} value={m.instructions} onChange={e => update({ instructions: e.target.value })} /></Field></div>; })}</TabsContent>
      <TabsContent value="procedures"><div className="mp-section-heading"><h3>Services / procedures performed</h3><AddButton onClick={() => change({ procedures: [...value.procedures, { id: uid(), name: '', result: '', explanation: '' }] })}>Add service</AddButton></div>{value.procedures.length === 0 && <p className="mp-empty-inline">No additional services are recorded.</p>}{value.procedures.map((p, i) => { const update = (patch: Partial<typeof p>) => change({ procedures: value.procedures.map((x, j) => i === j ? { ...x, ...patch } : x) }); return <div className="mp-form-row" key={p.id}><div className="mp-row-title"><strong>Service {i+1}</strong><RemoveButton label={`Remove service ${i+1}`} onClick={() => change({ procedures: value.procedures.filter((_, j) => i !== j) })} /></div><Field label="Clinical name *"><Input value={p.name} onChange={e => update({ name: e.target.value })} /></Field><Field label="Result / service details"><textarea className="mp-input" rows={3} value={p.result} onChange={e => update({ result: e.target.value })} /></Field><Field label="Plain-language explanation"><textarea className="mp-input" rows={2} value={p.explanation} onChange={e => update({ explanation: e.target.value })} /></Field></div>; })}</TabsContent>
      <TabsContent value="doctor"><Field label="Choose an existing clinician"><select className="mp-input" value={doctors.some(d => d.id === value.clinician.id) ? value.clinician.id : ''} onChange={e => { const doctor = doctors.find(d => d.id === e.target.value); change({ clinician: doctor ? { ...doctor } : { id: uid(), name: '', specialty: '', facility: '', public_phone: '', registration: '' } }); }}><option value="">Enter a new clinician</option>{doctors.map(d => <option value={d.id} key={d.id}>{d.name} · {d.facility}</option>)}</select></Field><div className="mp-form-grid">{([['name','Clinician name *'],['specialty','Specialty'],['facility','Hospital / clinic *'],['public_phone','Public contact number'],['registration','License / public registration information']] as const).map(([key,label]) => <Field key={key} label={label}><Input value={value.clinician[key]} onChange={e => doctorChange({ [key]: e.target.value })} /></Field>)}</div><p className="mp-footnote">The clinician snapshot is preserved with the visit so the patient knows who provided care and prescribed medication.</p></TabsContent>
    </Tabs></fieldset><ErrorBox message={error} /><div className="mp-form-footer"><span>{dirty ? 'Unsaved changes' : 'One complete visit record'}</span><Button type="button" variant="outline" disabled={saving} onClick={close}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? 'Saving visit…' : 'Save visit'}</Button></div></form>
  </DialogContent></Dialog>;
}
