'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from '@/components/app-link';
import MediPassBrand from '@/components/medipass-brand';
import { ArrowLeft, Download, MessageSquare, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { feedbackStatuses, feedbackCategories, type Feedback } from '@/lib/portal-types';
import { api, Busy, ErrorBox, formatDate, Field } from '../portal/portal-ui';

export default function FeedbackPage() {
  const [requests, setRequests] = useState<Feedback[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [filter, setFilter] = useState('all'), [editing, setEditing] = useState<Feedback | null>(null), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const result = await api<{ requests: Feedback[] }>('/api/feedback'); setRequests(result.requests); setError(''); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(load); const handler = () => { void load(); }; window.addEventListener('medipass-feedback-saved', handler); return () => window.removeEventListener('medipass-feedback-saved', handler); }, [load]);
  async function save() {
    if (!editing) return; setSaving(true); setError('');
    try { const data = await api<{ request: Feedback }>('/api/feedback', editing); setRequests(old => old.map(r => r.id === data.request.id ? data.request : r)); setEditing(null); } catch (e) { setError((e as Error).message); } finally { setSaving(false); }
  }
  function exportRequests() {
    const blob = new Blob([JSON.stringify({ exported_at: new Date().toISOString(), requests }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'medipass-yeu-cau-chinh-sua.json'; a.click(); URL.revokeObjectURL(url);
  }
  return <main className="mp-standalone"><nav className="mb-8 flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 pb-5 dark:border-slate-800" aria-label="Feedback navigation"><Link href="/" className="inline-flex rounded-xl focus-visible:outline-2 focus-visible:outline-blue-600"><MediPassBrand /></Link><Link className="inline-flex min-h-11 items-center gap-2 text-sm text-slate-600 hover:text-blue-600 dark:text-slate-300" href="/editor"><ArrowLeft size={17} />Back to clinical portal</Link></nav><header className="mp-page-heading"><div><p className="mp-eyebrow">HELP IMPROVE MEDIPASS</p><h1>Change requests</h1><p>Keep every comment, target location, and progress update in one place.</p></div><div className="mp-inline-actions"><Button variant="outline" onClick={exportRequests} disabled={!requests.length}><Download />Export list</Button><Link className="mp-button" href="/editor?annotate=1"><Plus />Select an area to comment</Link></div></header>
    <div className="mp-feedback-summary">{Object.entries(feedbackStatuses).map(([key,label]) => <button key={key} className={filter === key ? 'selected' : ''} onClick={() => setFilter(filter === key ? 'all' : key)}><strong>{requests.filter(r => r.status === key).length}</strong><span>{label}</span></button>)}</div>
    <div className="mp-section-heading"><h2>{filter === 'all' ? 'All requests' : feedbackStatuses[filter as keyof typeof feedbackStatuses]}</h2>{filter !== 'all' && <Button variant="ghost" onClick={() => setFilter('all')}>View all</Button>}</div><ErrorBox message={error} />{loading ? <Busy /> : <div className="mp-feedback-list">{requests.filter(r => filter === 'all' || r.status === filter).map(request => <article key={request.id} className="mp-panel"><div className="mp-feedback-card-heading"><div><div className="mp-inline-actions"><span className="mp-badge">{feedbackCategories[request.category as keyof typeof feedbackCategories]}</span>{request.priority === 'high' && <span className="mp-badge rose">High priority</span>}<span className={`mp-badge ${request.status === 'done' ? 'teal' : ''}`}>{feedbackStatuses[request.status as keyof typeof feedbackStatuses]}</span></div><h3>{request.title}</h3></div><Button variant="outline" disabled={saving} onClick={() => setEditing({ ...request })}>Update</Button></div><p className="mp-preserve">{request.description}</p><div className="mp-feedback-context">{request.section && <span>Area: {request.section}</span>}<Link href={`${request.page_path || '/'}${request.page_path?.includes('?') ? '&' : '?'}review=${request.id}`}>Open target area ↗</Link><span>{formatDate(request.created_at)}</span></div>{request.resolution && <p className="mp-clinician-note mp-preserve"><b>Response / outcome:</b> {request.resolution}</p>}{editing?.id === request.id && <div className="mp-feedback-edit"><Field label="Status"><select className="mp-input" value={editing.status} onChange={e => setEditing({ ...editing, status: e.target.value })}>{Object.entries(feedbackStatuses).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="Request details"><textarea className="mp-input" rows={4} value={editing.description} onChange={e => setEditing({ ...editing, description: e.target.value })} /></Field><Field label="Resolution notes"><textarea className="mp-input" rows={3} value={editing.resolution} onChange={e => setEditing({ ...editing, resolution: e.target.value })} /></Field><div className="mp-inline-actions"><Button disabled={saving} onClick={() => void save()}>{saving ? 'Saving…' : 'Save update'}</Button><Button variant="outline" disabled={saving} onClick={() => setEditing(null)}>Cancel</Button></div></div>}</article>)}{requests.filter(r => filter === 'all' || r.status === filter).length === 0 && <div className="mp-empty-card"><MessageSquare /><h3>No requests in this category</h3><p>Turn on “Annotate interface,” then select the area you want to change.</p></div>}</div>}
    <p className="mp-footnote">Feedback is stored for review during a future work session. The website does not run an assistant in the background.</p>
  </main>;
}
