'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from '@/components/app-link';
import { ArrowLeft, Download, MessageSquare, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { feedbackStatuses, feedbackCategories, type Feedback } from '@/lib/portal-types';
import { api, Busy, ErrorBox, formatDate, Field } from '../portal/portal-ui';

export default function FeedbackPage() {
  const [requests, setRequests] = useState<Feedback[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [filter, setFilter] = useState('all'), [editing, setEditing] = useState<Feedback | null>(null), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const result = await api<{ requests: Feedback[] }>('/api/feedback'); setRequests(result.requests); setError(''); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(load); const handler = () => { void load(); }; window.addEventListener('medipass-feedback-saved', handler); return () => window.removeEventListener('medipass-feedback-saved', handler); }, [load]);
  async function save() {
    if (!editing) return; setSaving(true); setError('');
    try { const data = await api<{ request: Feedback }>('/api/feedback', editing); setRequests(old => old.map(r => r.id === data.request.id ? data.request : r)); setEditing(null); } catch (e) { setError((e as Error).message); } finally { setSaving(false); }
  }
  function exportRequests() {
    const blob = new Blob([JSON.stringify({ exported_at: new Date().toISOString(), requests }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'medipass-yeu-cau-chinh-sua.json'; a.click(); URL.revokeObjectURL(url);
  }
  return <main className="mp-standalone"><Link className="mp-back" href="/editor"><ArrowLeft size={17} />Về cổng bệnh viện</Link><header className="mp-page-heading"><div><p className="mp-eyebrow">CÙNG HOÀN THIỆN MEDIPASS</p><h1>Yêu cầu chỉnh sửa</h1><p>Mọi góp ý, vị trí cần sửa và tiến độ được giữ ở một nơi.</p></div><div className="mp-inline-actions"><Button variant="outline" onClick={exportRequests} disabled={!requests.length}><Download />Xuất danh sách</Button><Link className="mp-button" href="/editor?annotate=1"><Plus />Chọn vị trí để bình luận</Link></div></header>
    <div className="mp-feedback-summary">{Object.entries(feedbackStatuses).map(([key,label]) => <button key={key} className={filter === key ? 'selected' : ''} onClick={() => setFilter(filter === key ? 'all' : key)}><strong>{requests.filter(r => r.status === key).length}</strong><span>{label}</span></button>)}</div>
    <div className="mp-section-heading"><h2>{filter === 'all' ? 'Tất cả yêu cầu' : feedbackStatuses[filter as keyof typeof feedbackStatuses]}</h2>{filter !== 'all' && <Button variant="ghost" onClick={() => setFilter('all')}>Xem tất cả</Button>}</div><ErrorBox message={error} />{loading ? <Busy /> : <div className="mp-feedback-list">{requests.filter(r => filter === 'all' || r.status === filter).map(request => <article key={request.id} className="mp-panel"><div className="mp-feedback-card-heading"><div><div className="mp-inline-actions"><span className="mp-badge">{feedbackCategories[request.category as keyof typeof feedbackCategories]}</span>{request.priority === 'high' && <span className="mp-badge rose">Ưu tiên cao</span>}<span className={`mp-badge ${request.status === 'done' ? 'teal' : ''}`}>{feedbackStatuses[request.status as keyof typeof feedbackStatuses]}</span></div><h3>{request.title}</h3></div><Button variant="outline" disabled={saving} onClick={() => setEditing({ ...request })}>Cập nhật</Button></div><p className="mp-preserve">{request.description}</p><div className="mp-feedback-context">{request.section && <span>Khu vực: {request.section}</span>}<Link href={`${request.page_path || '/'}${request.page_path?.includes('?') ? '&' : '?'}review=${request.id}`}>Mở vị trí góp ý ↗</Link><span>{formatDate(request.created_at)}</span></div>{request.resolution && <p className="mp-clinician-note mp-preserve"><b>Phản hồi / kết quả:</b> {request.resolution}</p>}{editing?.id === request.id && <div className="mp-feedback-edit"><Field label="Trạng thái"><select className="mp-input" value={editing.status} onChange={e => setEditing({ ...editing, status: e.target.value })}>{Object.entries(feedbackStatuses).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="Nội dung yêu cầu"><textarea className="mp-input" rows={4} value={editing.description} onChange={e => setEditing({ ...editing, description: e.target.value })} /></Field><Field label="Ghi chú xử lý"><textarea className="mp-input" rows={3} value={editing.resolution} onChange={e => setEditing({ ...editing, resolution: e.target.value })} /></Field><div className="mp-inline-actions"><Button disabled={saving} onClick={() => void save()}>{saving ? 'Đang lưu…' : 'Lưu cập nhật'}</Button><Button variant="outline" disabled={saving} onClick={() => setEditing(null)}>Hủy</Button></div></div>}</article>)}{requests.filter(r => filter === 'all' || r.status === filter).length === 0 && <div className="mp-empty-card"><MessageSquare /><h3>Chưa có yêu cầu ở mục này</h3><p>Bật “Chú thích giao diện”, rồi bấm vào vùng bạn muốn chỉnh sửa.</p></div>}</div>}
    <p className="mp-footnote">Góp ý được lưu để đọc và xử lý trong phiên làm việc khi bạn yêu cầu. Website không tự chạy một trợ lý ở nền.</p>
  </main>;
}
